[2024-07-11T23:43:14.093+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T23:43:14.144+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_allogistic_dag.execute_ipynb scheduled__2024-07-11T15:00:00+00:00 [queued]>
[2024-07-11T23:43:14.177+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_allogistic_dag.execute_ipynb scheduled__2024-07-11T15:00:00+00:00 [queued]>
[2024-07-11T23:43:14.180+0700] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-07-11T23:43:14.267+0700] {taskinstance.py:2330} INFO - Executing <Task(PapermillOperator): execute_ipynb> on 2024-07-11 15:00:00+00:00
[2024-07-11T23:43:14.275+0700] {standard_task_runner.py:63} INFO - Started process 268236 to run task
[2024-07-11T23:43:14.279+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'update_allogistic_dag', 'execute_ipynb', 'scheduled__2024-07-11T15:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpdj40ncbj']
[2024-07-11T23:43:14.283+0700] {standard_task_runner.py:91} INFO - Job 22: Subtask execute_ipynb
[2024-07-11T23:43:14.464+0700] {task_command.py:426} INFO - Running <TaskInstance: update_allogistic_dag.execute_ipynb scheduled__2024-07-11T15:00:00+00:00 [running]> on host LWIN-ID-OCT22-0115.
[2024-07-11T23:43:14.657+0700] {logging_mixin.py:188} WARNING - /mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/utils/context.py:212 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-07-11T23:43:14.792+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='update_allogistic_dag' AIRFLOW_CTX_TASK_ID='execute_ipynb' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T15:00:00+00:00'
[2024-07-11T23:43:14.797+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T23:43:14.800+0700] {execute.py:83} INFO - Input Notebook:  /mnt/c/Users/Erland/Documents/GitHub/airflow/dags/allogisticompiler.ipynb
[2024-07-11T23:43:14.803+0700] {execute.py:84} INFO - Output Notebook: /mnt/c/Users/Erland/Documents/GitHub/airflow/dags/out-allogisticompiler.ipynb
[2024-07-11T23:43:14.878+0700] {execute.py:97} WARNING - Passed unknown parameter: execution_date
[2024-07-11T23:43:15.694+0700] {parameterize.py:114} WARNING - Input notebook does not contain a cell with tag 'parameters'
[2024-07-11T23:43:29.013+0700] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2024-07-11T23:47:29.143+0700] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-07-11T23:47:29.146+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-11T23:47:29.150+0700] {process_utils.py:132} INFO - Sending Signals.SIGTERM to group 268236. PIDs of all processes in the group: [268283, 268236]
[2024-07-11T23:47:29.153+0700] {process_utils.py:87} INFO - Sending the signal Signals.SIGTERM to group 268236
[2024-07-11T23:47:29.157+0700] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-07-11T23:47:31.805+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T23:47:31.830+0700] {process_utils.py:80} INFO - Process psutil.Process(pid=268283, status='terminated', started='23:43:20') (268283) terminated with exit code None
[2024-07-11T23:47:31.829+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/providers/papermill/operators/papermill.py", line 118, in execute
    pm.execute_notebook(
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/execute.py", line 116, in execute_notebook
    nb = papermill_engines.execute_notebook_with_engine(
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/engines.py", line 48, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/engines.py", line 370, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/engines.py", line 442, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/clientwrap.py", line 45, in execute
    self.papermill_execute_cells()
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/clientwrap.py", line 72, in papermill_execute_cells
    self.execute_cell(cell, index)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.10/selectors.py", line 469, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-07-11T23:47:31.919+0700] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=update_allogistic_dag, task_id=execute_ipynb, run_id=scheduled__2024-07-11T15:00:00+00:00, execution_date=20240711T150000, start_date=20240711T164314, end_date=20240711T164731
[2024-07-11T23:47:31.960+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 22 for task execute_ipynb ((sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('execute_ipynb', 'update_allogistic_dag', 'scheduled__2024-07-11T15:00:00+00:00', -1, '2024-07-11 16:43:14.148092', '2024-07-11 16:47:31.918529', 257)]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 268236)
[2024-07-11T23:47:32.005+0700] {process_utils.py:80} INFO - Process psutil.Process(pid=268236, status='terminated', exitcode=1, started='23:43:14') (268236) terminated with exit code 1
