[2024-07-11T23:37:23.277+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T23:37:23.296+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_allogistic_dag.execute_ipynb scheduled__2024-07-11T15:00:00+00:00 [queued]>
[2024-07-11T23:37:23.339+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_allogistic_dag.execute_ipynb scheduled__2024-07-11T15:00:00+00:00 [queued]>
[2024-07-11T23:37:23.341+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-11T23:37:23.399+0700] {taskinstance.py:2330} INFO - Executing <Task(PapermillOperator): execute_ipynb> on 2024-07-11 15:00:00+00:00
[2024-07-11T23:37:23.404+0700] {standard_task_runner.py:63} INFO - Started process 265604 to run task
[2024-07-11T23:37:23.407+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'update_allogistic_dag', 'execute_ipynb', 'scheduled__2024-07-11T15:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpcshaaig0']
[2024-07-11T23:37:23.410+0700] {standard_task_runner.py:91} INFO - Job 20: Subtask execute_ipynb
[2024-07-11T23:37:23.550+0700] {task_command.py:426} INFO - Running <TaskInstance: update_allogistic_dag.execute_ipynb scheduled__2024-07-11T15:00:00+00:00 [running]> on host LWIN-ID-OCT22-0115.
[2024-07-11T23:37:23.718+0700] {logging_mixin.py:188} WARNING - /mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/utils/context.py:212 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-07-11T23:37:23.808+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='update_allogistic_dag' AIRFLOW_CTX_TASK_ID='execute_ipynb' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T15:00:00+00:00'
[2024-07-11T23:37:23.811+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T23:37:23.814+0700] {execute.py:83} INFO - Input Notebook:  /mnt/c/Users/Erland/Documents/GitHub/airflow/dags/allogisticompiler.ipynb.ipynb
[2024-07-11T23:37:23.815+0700] {execute.py:84} INFO - Output Notebook: /mnt/c/Users/Erland/Documents/GitHub/airflow/dags/out-allogisticompiler.ipynb
[2024-07-11T23:37:23.819+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T23:37:23.821+0700] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/iorw.py", line 199, in read
    json.loads(path)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/providers/papermill/operators/papermill.py", line 118, in execute
    pm.execute_notebook(
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/execute.py", line 89, in execute_notebook
    nb = load_notebook_node(input_path)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/iorw.py", line 499, in load_notebook_node
    nb = nbformat.reads(papermill_io.read(notebook_path), as_version=4)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/iorw.py", line 96, in read
    notebook_metadata = self.get_handler(path, extensions).read(path)
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/iorw.py", line 203, in read
    raise e
  File "/mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/papermill/iorw.py", line 193, in read
    with open(path, encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/Erland/Documents/GitHub/airflow/dags/allogisticompiler.ipynb.ipynb'
[2024-07-11T23:37:23.866+0700] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=update_allogistic_dag, task_id=execute_ipynb, run_id=scheduled__2024-07-11T15:00:00+00:00, execution_date=20240711T150000, start_date=20240711T163723, end_date=20240711T163723
[2024-07-11T23:37:23.916+0700] {standard_task_runner.py:110} ERROR - Failed to execute job 20 for task execute_ipynb ([Errno 2] No such file or directory: '/mnt/c/Users/Erland/Documents/GitHub/airflow/dags/allogisticompiler.ipynb.ipynb'; 265604)
[2024-07-11T23:37:23.944+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-11T23:37:23.974+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T23:37:23.978+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-07-11T23:50:47.968+0700] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T23:50:47.988+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_allogistic_dag.execute_ipynb scheduled__2024-07-11T15:00:00+00:00 [queued]>
[2024-07-11T23:50:48.001+0700] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_allogistic_dag.execute_ipynb scheduled__2024-07-11T15:00:00+00:00 [queued]>
[2024-07-11T23:50:48.002+0700] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-11T23:50:48.041+0700] {taskinstance.py:2330} INFO - Executing <Task(PapermillOperator): execute_ipynb> on 2024-07-11 15:00:00+00:00
[2024-07-11T23:50:48.047+0700] {standard_task_runner.py:63} INFO - Started process 271540 to run task
[2024-07-11T23:50:48.051+0700] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'update_allogistic_dag', 'execute_ipynb', 'scheduled__2024-07-11T15:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/run_notebook.py', '--cfg-path', '/tmp/tmpce8p20zk']
[2024-07-11T23:50:48.053+0700] {standard_task_runner.py:91} INFO - Job 20: Subtask execute_ipynb
[2024-07-11T23:50:48.252+0700] {task_command.py:426} INFO - Running <TaskInstance: update_allogistic_dag.execute_ipynb scheduled__2024-07-11T15:00:00+00:00 [running]> on host LWIN-ID-OCT22-0115.
[2024-07-11T23:50:48.366+0700] {logging_mixin.py:188} WARNING - /mnt/c/Users/Erland/Documents/GitHub/airflow/py_env/lib/python3.10/site-packages/airflow/utils/context.py:212 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2024-07-11T23:50:48.427+0700] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='update_allogistic_dag' AIRFLOW_CTX_TASK_ID='execute_ipynb' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T15:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-11T15:00:00+00:00'
[2024-07-11T23:50:48.429+0700] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T23:50:48.430+0700] {execute.py:83} INFO - Input Notebook:  /mnt/c/Users/Erland/Documents/GitHub/airflow/dags/allogisticompiler.ipynb
[2024-07-11T23:50:48.431+0700] {execute.py:84} INFO - Output Notebook: /mnt/c/Users/Erland/Documents/GitHub/airflow/dags/out-allogisticompiler.ipynb
[2024-07-11T23:50:48.468+0700] {execute.py:97} WARNING - Passed unknown parameter: execution_date
[2024-07-11T23:50:49.220+0700] {parameterize.py:114} WARNING - Input notebook does not contain a cell with tag 'parameters'
[2024-07-11T23:51:02.321+0700] {clientwrap.py:44} INFO - Executing notebook with kernel: python3
[2024-07-11T23:54:05.234+0700] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T23:54:05.320+0700] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=update_allogistic_dag, task_id=execute_ipynb, run_id=scheduled__2024-07-11T15:00:00+00:00, execution_date=20240711T150000, start_date=20240711T165047, end_date=20240711T165405
[2024-07-11T23:54:05.395+0700] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-11T23:54:05.429+0700] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T23:54:05.436+0700] {local_task_job_runner.py:222} INFO - ::endgroup::
